//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncenter.BackOffice.Clients.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://flex1374-uat.flexnetoperations.com/flexnet/services/v1/UserOrgHierarchySer" +
            "vice")]
        public string Oncenter_BackOffice_Clients_Flexera_UserOrganizationHierachy_v1_UserOrgHierarchyService {
            get {
                return ((string)(this["Oncenter_BackOffice_Clients_Flexera_UserOrganizationHierachy_v1_UserOrgHierarchyS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://flex1374-uat.flexnetoperations.com/flexnet/services/v1/EntitlementOrderSer" +
            "vice")]
        public string Oncenter_BackOffice_Clients_Flexera_Entitlement_v1_EntitlementOrderService {
            get {
                return ((string)(this["Oncenter_BackOffice_Clients_Flexera_Entitlement_v1_EntitlementOrderService"]));
            }
        }
    }
}
